export type Locale = "en" | "ko";


export const links = {
  github: "https://github.com/nums-ai/causilo",
  model: "https://huggingface.co/nums-ai/causilo",
  linkedin: "https://www.linkedin.com/company/numsai",
  contact: "mailto:contact@nums.world",
} as const;

export const content = {
  en: {
    skip: "Skip to content",
    navigation: ["Home", "Use Cases", "Blog", "Careers"],
    contact: "Contact",
    menu: "Navigation menu",
    headline: ["From predictions", "To better decisions"],
    heroDescription: "We build a foundation model for structured data.",
    heroDescriptionSecond: "New predictions without starting from scratch.",
    backed: "Backed by",
    modelTitle: "Meet Causilo by Nums AI",
    modelDescription: "Causilo is a tabular foundation model (TFM) pretrained on millions of tasks to learn structured data. With Causilo, you can make infinite predictions without retraining or fine-tuning.",
    causiloTitle: "Top performance",
    causiloDescription: "Causilo outperforms tuned and ensembled tree models on TabArena. It achieves an Elo score of 1792.9 across classification and regression tasks.",
    benchmarkPlotLabel: "TabArena overall Elo: Causilo, Random Forest, XGBoost, CatBoost, and LightGBM",
    applicationsTitle: ["Different questions,", "the same model"],
    applicationsDescription: "Explore TabArena datasets across eight domains and see how Causilo compares with traditional machine learning models on real prediction tasks.",
    updatesTitle: "Connect with Nums AI",
    blogTitle: "Blog",
    blogDescription: "Read about Causilo releases, company milestones, and news from our team.",
    blogLink: "Read the blog",
    careersTitle: "Careers",
    careersDescription: "Join our team in Seoul to build Causilo, bring it to customers, or propose a role of your own.",
    careersLink: "Explore careers",
    contactDescription: "Work with us to apply Causilo to your data, explore a research collaboration, or solve a new prediction problem.",
    footerDescription: "Tabular foundation models. Built in Seoul.",
    location: "Seoul, South Korea",
  },
  ko: {
    skip: "본문으로 건너뛰기",
    navigation: ["홈", "활용 사례", "블로그", "채용"],
    contact: "문의",
    menu: "메뉴",
    headline: ["예측에서", "더 나은 결정으로"],
    heroDescription: "정형 데이터를 위한 파운데이션 모델을 만듭니다.",
    heroDescriptionSecond: "매번 처음부터 학습할 필요 없이 새로운 예측을.",
    backed: "함께하는 투자사",
    modelTitle: "Nums AI의 Causilo를 소개합니다",
    modelDescription: "Causilo는 정형 데이터의 패턴을 학습하기 위해 수백만 개의 과제로 사전 학습된 테이블 파운데이션 모델(TFM)입니다. Causilo를 사용하면 재학습이나 파인튜닝 없이 무한한 예측을 할 수 있습니다.",
    causiloTitle: "최고의 성능",
    causiloDescription: "Causilo는 TabArena에서 튜닝과 앙상블을 적용한 트리 모델을 뛰어넘는 성능을 보입니다. 분류와 회귀 과제를 아우르는 평가에서 Elo 점수 1792.9를 달성합니다.",
    benchmarkPlotLabel: "TabArena 종합 Elo: Causilo, Random Forest, XGBoost, CatBoost, LightGBM",
    applicationsTitle: ["서로 다른 질문,", "하나의 모델"],
    applicationsDescription: "여덟 분야의 TabArena 데이터셋을 살펴보고, 실제 예측 과제에서 Causilo와 기존 머신러닝 모델의 성능을 비교해 보세요.",
    updatesTitle: "Nums AI와 함께하세요",
    blogTitle: "블로그",
    blogDescription: "Causilo의 새로운 소식부터 회사의 주요 성과까지, Nums AI 팀의 이야기를 전합니다.",
    blogLink: "블로그 읽기",
    careersTitle: "채용",
    careersDescription: "서울에서 Causilo를 만들고 고객의 문제를 해결할 동료를 찾습니다. 채용 중인 직무를 살펴보거나 새로운 역할을 제안해 주세요.",
    careersLink: "채용 페이지 살펴보기",
    contactDescription: "보유한 데이터에 Causilo를 적용하거나, 공동 연구를 시작하거나, 새로운 예측 문제를 해결하는 방법을 함께 논의해 보세요.",
    footerDescription: "서울에서 만드는 테이블 파운데이션 모델.",
    location: "대한민국 서울",
  },
} as const;
